export const R2_BASE = "https://videos.openhero.art";

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export interface PreviewTarget {
  category: string;
  slug: string;
  /**
   * Where the HTML came from, which decides where its video lives in R2:
   * - "curated": handcrafted hero from public/downloads → downloads/{cat}/{slug}/video.mp4
   * - "studio": generated by the template engine → videos/{cat}/{slug}.mp4 (+ .jpg poster)
   */
  variant?: "curated" | "studio";
}

/**
 * Rewrites the local asset paths in a hero's HTML so it can render in a live
 * preview (iframe or the /preview route) against the R2-hosted media.
 */
export function toPreviewHtml(html: string, { category, slug, variant = "curated" }: PreviewTarget): string {
  const cat = escapeRegExp(category);
  const slg = escapeRegExp(slug);
  const galleryVideo = `${R2_BASE}/videos/${category}/${slug}.mp4`;
  const galleryPoster = `${R2_BASE}/videos/${category}/${slug}.jpg`;
  const downloadVideo = `${R2_BASE}/downloads/${category}/${slug}/video.mp4`;
  // Studio templates ship relative ./video.mp4 next to the HTML; in the live
  // preview that maps to the gallery copy. Curated heroes use the downloads copy.
  const relativeVideo = variant === "studio" ? galleryVideo : downloadVideo;

  return html
    // Relative assets (./video.mp4 / ./poster.jpg and the /video.mp4 legacy form).
    .replace(/src=["']\.\/video\.mp4["']/gi, `src="${relativeVideo}"`)
    .replace(/src=["']\/video\.mp4["']/gi, `src="${relativeVideo}"`)
    .replace(/poster=["']\.\/poster\.jpg["']/gi, `poster="${galleryPoster}"`)
    // Absolute /videos paths (older generated output / Next-style references).
    .replace(
      new RegExp(`(src|poster)=(["'])/videos/${cat}/${slg}\\.mp4\\2`, "gi"),
      `$1=$2${galleryVideo}$2`,
    )
    .replace(
      new RegExp(`(src|poster)=(["'])/videos/${cat}/${slg}\\.jpg\\2`, "gi"),
      `$1=$2${galleryPoster}$2`,
    )
    // Curated heroes occasionally inline full /downloads/... paths.
    .replace(/src=["']\/downloads\/[^"']+["']/gi, `src="${downloadVideo}"`);
}
